// Draws Kindred's icon set.
//
// The app shipped with create-expo-app's blue Expo logo in every slot. This
// replaces all of them with one mark — a candle flame, the thing the whole
// palette is named after — rendered at each size the platforms ask for.
//
// It is plain Node with no dependencies: the shape is an implicit function, and
// the PNG is encoded by hand on top of zlib. That is deliberate. An icon set
// that can only be regenerated by opening a design tool is an icon set that
// drifts, and adding an image library to a project that has no other use for one
// costs more than the sixty lines below.
//
//   node scripts/generate-icons.js
//
// Everything it writes is committed; this only needs running when the mark or
// the palette changes.

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

// Straight from src/theme/tokens.ts. Keep them in step.
const LINEN = [0xf6, 0xf3, 0xea]; // bg
const FLAME_BOTTOM = [0xed, 0xa3, 0x3d]; // flame (light)
const FLAME_TOP = [0xf0, 0xb0, 0x54]; // flame (dark theme) — the lighter tip
const BLACK = [0x00, 0x00, 0x00];
const WHITE = [0xff, 0xff, 0xff];

// How wide the flame is relative to its height. Taller than wide, or it reads
// as a raindrop.
const WIDTH_RATIO = 0.28;

// Samples per pixel per axis. Four is enough to hide the stair-stepping at 48px,
// which is the smallest size anything here is drawn at.
const SS = 4;

// ---------------------------------------------------------------- the shape

// A flame as a circle with a cone drawn onto it: the round bottom is the
// circle, and the point is where the two tangent lines from the tip meet it.
// The tangent construction is what keeps the join smooth — a cone at any other
// angle leaves a visible corner where the straight edge hits the curve.
function flame({ tipX, tipY, height }) {
  const radius = height * WIDTH_RATIO;
  const centreX = tipX;
  const centreY = tipY + height - radius;

  // Distance from the tip to the centre, and the length of a tangent from it.
  const d = height - radius;
  const tangent = Math.sqrt(d * d - radius * radius);

  // How far down the axis the tangent points sit, and how far out they reach.
  const axisMax = (tangent * tangent) / d;
  const spread = radius / tangent;

  return function inside(x, y) {
    const dx = x - centreX;
    const dy = y - centreY;
    if (dx * dx + dy * dy <= radius * radius) return true;

    const along = y - tipY;
    if (along < 0 || along > axisMax) return false;
    return Math.abs(x - tipX) <= along * spread;
  };
}

// ---------------------------------------------------------------- rendering

function lerp(a, b, t) {
  return a.map((v, i) => Math.round(v + (b[i] - v) * t));
}

// One image. `ground` fills every pixel and makes the result opaque; without it
// the flame is drawn on transparency. `tint` overrides the gradient with a flat
// colour, which is what the monochrome and notification variants need.
function draw({ width, height, tipY, flameHeight, ground, tint }) {
  const px = Buffer.alloc(width * height * 4);
  const shape = flame({ tipX: width / 2, tipY, height: flameHeight });

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      let hits = 0;
      for (let sy = 0; sy < SS; sy++) {
        for (let sx = 0; sx < SS; sx++) {
          if (shape(x + (sx + 0.5) / SS, y + (sy + 0.5) / SS)) hits++;
        }
      }

      const coverage = hits / (SS * SS);
      const i = (y * width + x) * 4;

      // Down the flame rather than down the canvas, so the gradient reads the
      // same however much padding a given size happens to have.
      const t = Math.min(1, Math.max(0, (y - tipY) / flameHeight));
      const mark = tint ?? lerp(FLAME_TOP, FLAME_BOTTOM, t);

      if (ground) {
        const blended = lerp(ground, mark, coverage);
        px[i] = blended[0];
        px[i + 1] = blended[1];
        px[i + 2] = blended[2];
        px[i + 3] = 255;
      } else {
        px[i] = mark[0];
        px[i + 1] = mark[1];
        px[i + 2] = mark[2];
        px[i + 3] = Math.round(coverage * 255);
      }
    }
  }

  return { width, height, px };
}

// ---------------------------------------------------------------- PNG output

const CRC_TABLE = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c;
  }
  return table;
})();

function crc32(buf) {
  let c = -1;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ -1) >>> 0;
}

function chunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([length, body, crc]);
}

function encodePNG({ width, height, px }) {
  const header = Buffer.alloc(13);
  header.writeUInt32BE(width, 0);
  header.writeUInt32BE(height, 4);
  header[8] = 8; // bit depth
  header[9] = 6; // colour type: RGBA
  header[10] = 0; // deflate
  header[11] = 0; // adaptive filtering
  header[12] = 0; // no interlace

  // One filter byte per scanline. Filter 0 (none) — the shapes are smooth and
  // deflate handles them well enough that choosing a filter per row would only
  // buy a few kilobytes.
  const stride = width * 4;
  const raw = Buffer.alloc((stride + 1) * height);
  for (let y = 0; y < height; y++) {
    raw[y * (stride + 1)] = 0;
    px.copy(raw, y * (stride + 1) + 1, y * stride, (y + 1) * stride);
  }

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', header),
    chunk('IDAT', zlib.deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

// ---------------------------------------------------------------- the set

const OUT = path.join(__dirname, '..', 'assets', 'images');

// `scale` is the flame's height as a fraction of the canvas.
//
// The adaptive icon is the odd one out: Android crops a 108dp canvas down to
// roughly its middle two thirds, so its mark has to be small enough to survive
// whatever shape the launcher decides to use. The notification icon is the
// other extreme — a 24dp status bar slot where anything but a nearly
// full-bleed mark disappears.
const SIZES = [
  { file: 'icon.png', size: 1024, scale: 0.6, ground: LINEN },
  { file: 'favicon.png', size: 48, scale: 0.72, ground: LINEN },
  { file: 'android-icon-foreground.png', size: 512, scale: 0.5 },
  { file: 'android-icon-monochrome.png', size: 432, scale: 0.5, tint: BLACK },
  { file: 'notification-icon.png', size: 96, scale: 0.84, tint: WHITE },
];

function report(file, image) {
  const { width, height, px } = image;
  let opaque = 0;
  let clear = 0;
  let minX = width;
  let minY = height;
  let maxX = 0;
  let maxY = 0;

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const a = px[(y * width + x) * 4 + 3];
      if (a === 0) clear++;
      if (a > 127) {
        opaque++;
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
        if (y < minY) minY = y;
        if (y > maxY) maxY = y;
      }
    }
  }

  const pct = (n) => `${((100 * n) / (width * height)).toFixed(0)}%`;
  console.log(
    `${file.padEnd(32)} ${width}x${height}  transparent ${pct(clear).padStart(4)}` +
      `  mark ${maxX - minX + 1}x${maxY - minY + 1}`,
  );
}

function main() {
  for (const { file, size, scale, ground, tint } of SIZES) {
    const flameHeight = size * scale;
    const image = draw({
      width: size,
      height: size,
      tipY: (size - flameHeight) / 2,
      flameHeight,
      ground,
      tint,
    });
    fs.writeFileSync(path.join(OUT, file), encodePNG(image));
    report(file, image);
  }

  // The splash mark is cropped to the flame instead of centred in a square:
  // expo-splash-screen scales the file to `imageWidth`, so padding baked into
  // the image would only make the flame smaller than the number asks for.
  const splashHeight = 256;
  const pad = Math.round(splashHeight * 0.08);
  const splashWidth = Math.round(splashHeight * WIDTH_RATIO * 2) + pad * 2;
  const splash = draw({
    width: splashWidth,
    height: splashHeight + pad * 2,
    tipY: pad,
    flameHeight: splashHeight,
  });
  fs.writeFileSync(path.join(OUT, 'splash-icon.png'), encodePNG(splash));
  report('splash-icon.png', splash);
}

main();
